import uuid
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, ConfigDict


class StepExecutionContext(BaseModel):
    """
    Execution context provided to a step executor.
    Previous step outputs in workflow_data are treated as a read-only snapshot.
    """
    organization_id: uuid.UUID
    workflow_run_id: uuid.UUID
    step_id: uuid.UUID
    step_key: str
    step_type: str
    config: Dict[str, Any] = Field(default_factory=dict)
    workflow_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Snapshot of accumulated outputs from upstream completed steps",
    )
    trigger_payload: Dict[str, Any] = Field(
        default_factory=dict,
        description="Original trigger payload for the workflow run",
    )

    model_config = ConfigDict(frozen=True)


class StepExecutionResult(BaseModel):
    """
    Result returned by a step executor after discrete execution.
    """
    status: str = Field(..., description="COMPLETED | FAILED | PAUSED | SKIPPED")
    output_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Data generated by this step to pass downstream",
    )
    error_message: Optional[str] = Field(
        None,
        description="Error description if status is FAILED",
    )
    execution_time_ms: int = Field(
        0,
        description="Step execution duration in milliseconds",
    )
    selected_branch: Optional[str] = Field(
        None,
        description="Condition branch label selected ('true', 'false', etc.)",
    )
    requires_approval: bool = Field(
        False,
        description="True if step suspends execution for human approval",
    )
    approval_context: Optional[Dict[str, Any]] = Field(
        None,
        description="Contextual payload for human approval review",
    )

    model_config = ConfigDict(arbitrary_types_allowed=True)


class BaseStepExecutor(ABC):
    """
    Abstract interface for all workflow step executors.
    Every executor must be deterministic, stateless, and independently testable.
    """

    @abstractmethod
    async def execute(self, ctx: StepExecutionContext) -> StepExecutionResult:
        """
        Executes discrete step logic asynchronously.
        """
        pass
